### ISSUE TITLE
TwinMaker Scene Viewer: Tag icon not following its rule

### ISSUE THREAD

**Issue by DanielePancottini** [grafana/grafana-iot-twinmaker-app#220]
### What happened?

I have got two tag icons inside a twinmaker scene viewer panel that aren't updating. I think the data source is correctly configurated because I can see the correct data within other panels (using the same twinmaker component and properties)

### What did you expect to happen?

I have got a dht sensor that publishes humidity and temperature into a timestream database. In my twinmaker scene, there are two tags linked to humidity and temperature data, and I need to make their icons change to alert state if data crosses a certain threshold

### Did this work before?

The twinmaker scene viewer never worked, but the other panels which are using the same component and the same properties are working

### How do we reproduce it?

1. Create TwinMaker Scene Viewer Panel
2. Link it with my twinmaker scene (containing my 3d model and my two tags for humidity and temperature)
3. Create two queries to get humidity and temperature properties 

### Is the bug inside a dashboard panel?

| Key | Value |
|--|--|
| Panel | grafana-iot-twinmaker-sceneviewer-panel @ 9.4.7 (v9.4.7-aws-2023-08-30-175600-ent-dffedc6-oss-373c73a) |
| Grafana | 9.4.7 (v9.4.7-aws-2023-08-30-175600-ent-dffedc6-oss-373c73a) // Pro |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "datasource": "",
        "sceneId": "MainScene"
      },
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "meta": {
                  "custom": {}
                },
                "fields": [
                  {
                    "name": "temperature",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64",
                      "nullable": true
                    },
                    "labels": {
                      "componentName": "timestream-reader",
                      "entityId": "09c1322a-3c3b-4be8-ac20-ff18ae334daf",
                      "propertyName": "temperature"
                    },
                    "config": {}
                  },
                  {
                    "name": "Time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time",
                      "nullable": true
                    },
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    24.5,
                    24.5,
                    24.5,
                    24.5,
                    24.5,
                    24.8,
                    24.8,
                    24.8,
                    24.8,
                    24.8,
                    25.3
                  ],
                  [
                    1695109155812,
                    1695109514667,
                    1695109875593,
                    1695110235325,
                    1695110595093,
                    1695110955935,
                    1695111315744,
                    1695111676515,
                    1695112036330,
                    1695112396319,
                    1695114498279
                  ]
                ]
              }
            },
            {
              "schema": {
                "refId": "B",
                "meta": {
                  "custom": {}
                },
                "fields": [
                  {
                    "name": "humidity",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64",
                      "nullable": true
                    },
                    "labels": {
                      "componentName": "timestream-reader",
                      "entityId": "09c1322a-3c3b-4be8-ac20-ff18ae334daf",
                      "propertyName": "humidity"
                    },
                    "config": {}
                  },
                  {
                    "name": "Time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time",
                      "nullable": true
                    },
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    70,
                    71,
                    71,
                    71,
                    71,
                    71,
                    71,
                    72,
                    72,
                    72,
                    72
                  ],
                  [
                    1695109155812,
                    1695109514667,
                    1695109875593,
                    1695110235325,
                    1695110595093,
                    1695110955935,
                    1695111315744,
                    1695111676515,
                    1695112036330,
                    1695112396319,
                    1695114498279
                  ]
                ]
              }
            }
          ]
        }
      ],
      "title": "Reproduced with embedded data",
      "type": "grafana-iot-twinmaker-sceneviewer-panel"
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >grafana-iot-twinmaker-sceneviewer-panel @ 9.4.7 (v9.4.7-aws-2023-08-30-175600-ent-dffedc6-oss-373c73a)</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[grafana-iot-twinmaker-datasource], B[grafana-iot-twinmaker-datasource]</td>\n    </tr>\n    \n    <tr><th>Data</th><td> 2 frames, 4 fields, 22 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>9.4.7 (v9.4.7-aws-2023-08-30-175600-ent-dffedc6-oss-373c73a) // Pro</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"datasource\": {\n    \"type\": \"grafana-iot-twinmaker-datasource\",\n    \"uid\": \"be2_TPmIz\"\n  },\n  \"gridPos\": {\n    \"h\": 8,\n    \"w\": 12,\n    \"x\": 0,\n    \"y\": 8\n  },\n  \"id\": 12,\n  \"options\": {\n    \"datasource\": \"\",\n    \"sceneId\": \"MainScene\"\n  },\n  \"targets\": [\n    {\n      \"componentName\": \"DHT11-component\",\n      \"datasource\": {\n        \"type\": \"grafana-iot-twinmaker-datasource\",\n        \"uid\": \"be2_TPmIz\"\n      },\n      \"entityId\": \"09c1322a-3c3b-4be8-ac20-ff18ae334daf\",\n      \"properties\": [\n        \"temperature\"\n      ],\n      \"propertyDisplayNames\": {},\n      \"queryType\": \"EntityHistory\",\n      \"refId\": \"A\"\n    },\n    {\n      \"componentName\": \"DHT11-component\",\n      \"datasource\": {\n        \"type\": \"grafana-iot-twinmaker-datasource\",\n        \"uid\": \"be2_TPmIz\"\n      },\n      \"entityId\": \"09c1322a-3c3b-4be8-ac20-ff18ae334daf\",\n      \"hide\": false,\n      \"properties\": [\n        \"humidity\"\n      ],\n      \"propertyDisplayNames\": {},\n      \"queryType\": \"EntityHistory\",\n      \"refId\": \"B\"\n    }\n  ],\n  \"title\": \"TwinMaker\",\n  \"type\": \"grafana-iot-twinmaker-sceneviewer-panel\"\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: TwinMaker // 2023-09-19 18:02:09",
  "tags": [
    "debug",
    "debug-grafana-iot-twinmaker-sceneviewer-panel"
  ],
  "time": {
    "from": "2023-09-19T04:02:09.816Z",
    "to": "2023-09-19T16:02:09.816Z"
  }
}
```
</details>

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

AWS IoT TwinMaker App 1.6.2

**Comment by DanielePancottini** [comment]
Hi @kevinwcyu these are my rules, one for humidity and one for temperature

![Immagine 2023-09-20 214539](https://github.com/grafana/grafana-iot-twinmaker-app/assets/43572647/12778f84-d2b6-44cd-87fb-5112e6c1a400)

I'm updating the dashboard every 30 seconds

**Comment by hwandersman** [comment]
Can you show us the data binding on the respective tags that are using these rules? The property names have to match in the data binding and rule expression.

Can you also share a snippet of the data you are seeing on a Table panel for those properties?

What is the query you have on the Scene Viewer panel?

**Comment by DanielePancottini** [comment]
> Can you show us the data binding on the respective tags that are using these rules? The property names have to match in the data binding and rule expression.
> 
> Can you also share a snippet of the data you are seeing on a Table panel for those properties?
> 
> What is the query you have on the Scene Viewer panel?

Hi @hwandersman these are tags, data table and

![dataTable](https://github.com/grafana/grafana-iot-twinmaker-app/assets/43572647/7e76a08a-93b2-4dd1-b026-ee643c3f3fb1)
![grafanaQueries](https://github.com/grafana/grafana-iot-twinmaker-app/assets/43572647/7a2ff0e1-44ab-4dee-a287-9f360f15e180)
![temperatureTag](https://github.com/grafana/grafana-iot-twinmaker-app/assets/43572647/997a5b6e-dfab-468b-b3d4-063008bb0086)
![humidityTag](https://github.com/grafana/grafana-iot-twinmaker-app/assets/43572647/9071b814-c1a9-4a36-a81d-6dcffef5e9b3)
 queries

**Comment by sopanroy** [comment]
We are also facing the same issue recently. In twinmaker rule is set for icon change, but that is not reflecting in grafana scene viewer panel. Can someone please help.

**Comment by idastambuk** [comment]
@DanielePancottini are you facing the same issues as @sopanroy and does zooming in help? This would help us with debugging. Thanks!

**Comment by DanielePancottini** [comment]
> @DanielePancottini are you facing the same issues as @sopanroy and does zooming in help? This would help us with debugging. Thanks!

Unfortunately, my icons are not changing, even with the zoom in

**Comment by sopanroy** [comment]
Hi Team,
Just an update from my end, after going in Twinmaker Scene Composer and then Settings -> Tag Settings and change the Scale to 8, I can now see the icon in Grafana properly. Both cloud and docker local kit. Thanks anyway.

**Comment by Tigurius90** [comment]
I have exactly the same issue as @DanielePancottini, zooming does not help either...

**Comment by Tigurius90** [comment]
I think that it might be a bug in Grafana's AWS IoT TwinMaker Scene Viewer

**Comment by idastambuk** [comment]
The Twinmaker team is currently investigating the issue, we will update this ticket once we have more info

**Comment by hwandersman** [comment]
We just released a new plugin v1.8.0, I recommend you upgrade to that version: https://grafana.com/grafana/plugins/grafana-iot-twinmaker-app/?tab=changelog

In order for your tags in the Scene Viewer to change icons you must have the following set up:

In the AWS IoT TwinMaker Console scene composer:
1. Have a tag with an entity, component, and property assigned
2. Have a rule defined with an expression that uses the exact same name as the property
3. Attach that rule to the tag

In Grafana on the Scene Viewer panel:
1. Have a query for "Get Property Value History by Entity" with the same entity, component, and property path as on the tag in your scene
2. Verify that there is data returned for the query for the dashboard time range
3. The **latest** value of the data matches the rule expression in your scene
4. The Scene Viewer panel is configured with the same datasource as the query to load your scene

If you meet all of this criteria and are still running into issues I would be happy to meet with you to further debug. You can email me at hwanders@amazon.com to set up a time to meet virtually.

**Comment by DanielePancottini** [comment]
> We just released a new plugin v1.8.0, I recommend you upgrade to that version: https://grafana.com/grafana/plugins/grafana-iot-twinmaker-app/?tab=changelog
> 
> In order for your tags in the Scene Viewer to change icons you must have the following set up:
> 
> In the AWS IoT TwinMaker Console scene composer:
> 
> 1. Have a tag with an entity, component, and property assigned
> 2. Have a rule defined with an expression that uses the exact same name as the property
> 3. Attach that rule to the tag
> 
> In Grafana on the Scene Viewer panel:
> 
> 1. Have a query for "Get Property Value History by Entity" with the same entity, component, and property path as on the tag in your scene
> 2. Verify that there is data returned for the query for the dashboard time range
> 3. The **latest** value of the data matches the rule expression in your scene
> 4. The Scene Viewer panel is configured with the same datasource as the query to load your scene
> 
> If you meet all of this criteria and are still running into issues I would be happy to meet with you to further debug. You can email me at [hwanders@amazon.com](mailto:hwanders@amazon.com) to set up a time to meet virtually.

I've checked all your steps but unfortunately the problem isn't fixed yet

**Comment by varun-verma-mk** [comment]
> We just released a new plugin v1.8.0, I recommend you upgrade to that version: https://grafana.com/grafana/plugins/grafana-iot-twinmaker-app/?tab=changelog
> 
> In order for your tags in the Scene Viewer to change icons you must have the following set up:
> 
> In the AWS IoT TwinMaker Console scene composer:
> 
> 1. Have a tag with an entity, component, and property assigned
> 2. Have a rule defined with an expression that uses the exact same name as the property
> 3. Attach that rule to the tag
> 
> In Grafana on the Scene Viewer panel:
> 
> 1. Have a query for "Get Property Value History by Entity" with the same entity, component, and property path as on the tag in your scene
> 2. Verify that there is data returned for the query for the dashboard time range
> 3. The **latest** value of the data matches the rule expression in your scene
> 4. The Scene Viewer panel is configured with the same datasource as the query to load your scene
> 
> If you meet all of this criteria and are still running into issues I would be happy to meet with you to further debug. You can email me at [hwanders@amazon.com](mailto:hwanders@amazon.com) to set up a time to meet virtually.

I have also tried all these steps and am using the latest plugin v1.8.1. The tags don't reflect the data update

**Comment by Tigurius90** [comment]
Hi All,

I could fix the issue. I was following this [tutorial ](https://aws.amazon.com/blogs/iot/build-a-digital-twin-of-your-iot-device-and-monitor-real-time-sensor-data-using-aws-iot-twinmaker-part-2-of-2/) in order to build the model. @hwandersman  identified that the issue was in the connector, the lambda function that sends the data from Timestream to AWS IoT TwinMaker. The component name of the lambda function should match the component name of AWS IoT TwinMaker. So, in the code below, "timestream-reader" should be replaced by the component name that you gave in AWS IoT TwinMaker.

![image](https://github.com/grafana/grafana-iot-twinmaker-app/assets/112919139/e25e6d1e-ac59-4d0a-bd15-dd9b6439c02d)


![image](https://github.com/grafana/grafana-iot-twinmaker-app/assets/112919139/6d5528c4-2c42-49a0-95b5-6900be29ea80)

In addition, there is also another error in the code which is that the start and end quotes are not the same type in the string humidity and temperature.

![image](https://github.com/grafana/grafana-iot-twinmaker-app/assets/112919139/6bf9bb20-b185-4785-8d82-a89d51b5c0ff)

Thank you @hwandersman for your great help and support.

**Comment by hwandersman** [comment]
Reached out to the blog author and he will fix this soon!

@DanielePancottini @varun-verma-mk let me know if this resolves your issue.

**Comment by DanielePancottini** [comment]
> Hi All,
> 
> I could fix the issue. I was following this [tutorial ](https://aws.amazon.com/blogs/iot/build-a-digital-twin-of-your-iot-device-and-monitor-real-time-sensor-data-using-aws-iot-twinmaker-part-2-of-2/) in order to build the model. @hwandersman identified that the issue was in the connector, the lambda function that sends the data from Timestream to AWS IoT TwinMaker. The component name of the lambda function should match the component name of AWS IoT TwinMaker. So, in the code below, "timestream-reader" should be replaced by the component name that you gave in AWS IoT TwinMaker.
> 
> ![image](https://user-images.githubusercontent.com/112919139/272061250-e25e6d1e-ac59-4d0a-bd15-dd9b6439c02d.png)
> 
> ![image](https://user-images.githubusercontent.com/112919139/272061909-6d5528c4-2c42-49a0-95b5-6900be29ea80.png)
> 
> In addition, there is also another error in the code which is that the start and end quotes are not the same type in the string humidity and temperature.
> 
> ![image](https://user-images.githubusercontent.com/112919139/272062306-6bf9bb20-b185-4785-8d82-a89d51b5c0ff.png)
> 
> Thank you @hwandersman for your great help and support.

Wow, thank you, really, change the component name solved my problem

**Comment by varun-verma-mk** [comment]
> Reached out to the blog author and he will fix this soon!
> 
> @DanielePancottini @varun-verma-mk let me know if this resolves your issue.

Yes! that works like a charm.  ('componentName' mis-match was the problem)
Thanks a lot @hwandersman appreciate all the comms and help.
